"""
Exercise 5.1 — Human-in-the-Loop: The agent that asks permission.

Graph topology:

    plan ──► [PAUSE] ──► execute ──► END
                            │
                          approved?
                          no  → result = CANCELLED

The graph is compiled with interrupt_before=["execute"].
LangGraph stops after plan_node completes and before execute_node starts.
The human inspects state["plan"], optionally updates state["approved"],
then resumes by calling graph.invoke(None, config=config).

MemorySaver stores the paused snapshot so resume works across calls
(or even across process restarts when using a persistent checkpointer).
"""

import os
from typing import TypedDict

from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import END, StateGraph

load_dotenv()

# ---------------------------------------------------------------------------
# State
# ---------------------------------------------------------------------------

class HITLState(TypedDict):
    task:     str    # the goal the agent is working toward (immutable after init)
    plan:     str    # action plan generated by plan_node
    approved: bool   # human sets this to True to authorise execution
    result:   str    # final output from execute_node


# ---------------------------------------------------------------------------
# LLM
# ---------------------------------------------------------------------------

llm = ChatOpenAI(
    model="llama-3.3-70b-versatile",
    base_url="https://api.groq.com/openai/v1",
    api_key=os.environ["GROQ_API_KEY"],
    max_tokens=1024,
)

# ---------------------------------------------------------------------------
# Nodes
# ---------------------------------------------------------------------------

def plan_node(state: HITLState) -> dict:
    """
    Generate a numbered action plan for the task.
    High-risk steps are flagged with [HIGH RISK].
    The graph pauses AFTER this node completes.
    """
    print(f"\n[plan] Generating plan for: {state['task']}")

    plan = llm.invoke(
        f"Generate a detailed, numbered action plan for the following task.\n"
        f"For each step include: what it does, what system it touches, and its "
        f"reversibility. Mark irreversible or high-impact steps with [HIGH RISK].\n\n"
        f"Task: {state['task']}"
    ).content.strip()

    print(f"\n--- Proposed Plan ---\n{plan}\n")
    return {"plan": plan}


def execute_node(state: HITLState) -> dict:
    """
    Execute the plan — but only if state["approved"] is True.
    If the human did not approve, return a CANCELLED result immediately.
    This node runs only after the human resumes the graph.
    """
    if not state.get("approved"):
        print("[execute] Not approved — cancelling.")
        return {"result": "CANCELLED — plan was not approved by the operator."}

    print("[execute] Plan approved. Executing...")

    result = llm.invoke(
        f"Simulate executing the following plan step by step.\n"
        f"For each step report the outcome (success / warning / error) "
        f"and any side effects.\n\n"
        f"Plan:\n{state['plan']}"
    ).content.strip()

    print(f"\n--- Execution Result ---\n{result[:400]}\n")
    return {"result": result}


# ---------------------------------------------------------------------------
# Graph — compiled with interrupt_before=["execute"] and MemorySaver
# ---------------------------------------------------------------------------

_builder = StateGraph(HITLState)
_builder.add_node("plan",    plan_node)
_builder.add_node("execute", execute_node)

_builder.set_entry_point("plan")
_builder.add_edge("plan",    "execute")
_builder.add_edge("execute", END)

memory = MemorySaver()

# interrupt_before=["execute"]:
#   LangGraph persists state after plan_node, then returns control to the caller.
#   The next graph.invoke(None, config) resumes from execute_node.
graph = _builder.compile(
    checkpointer=memory,
    interrupt_before=["execute"],
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _config(thread_id: str) -> dict:
    """LangGraph config dict that identifies the conversation thread."""
    return {"configurable": {"thread_id": thread_id}}


def get_current_state(thread_id: str) -> HITLState:
    """Read the paused state snapshot without resuming execution."""
    snapshot = graph.get_state(_config(thread_id))
    return snapshot.values


def approve(thread_id: str) -> None:
    """Inject approved=True into the paused state."""
    graph.update_state(_config(thread_id), {"approved": True})
    print(f"[hitl] Thread '{thread_id}' approved.")


def reject(thread_id: str) -> None:
    """Leave approved=False (the default); just marks intent for clarity."""
    print(f"[hitl] Thread '{thread_id}' rejected — will resume as CANCELLED.")


def resume(thread_id: str) -> HITLState:
    """Resume execution from the interrupt point and return the final state."""
    return graph.invoke(None, config=_config(thread_id))


# ---------------------------------------------------------------------------
# Demo
# ---------------------------------------------------------------------------

def demo_approved() -> None:
    """Full flow: plan → pause → human approves → execute."""
    thread = "hitl-approved"
    print(f"\n{'=' * 60}")
    print("DEMO 1 — Approved flow")
    print(f"{'=' * 60}")

    # ── Step 1: invoke — graph runs plan_node then pauses ──────────────
    print("\nStep 1: Invoke (graph pauses after planning)")
    graph.invoke(
        {
            "task":     "Delete all test users from the production database",
            "plan":     "",
            "approved": False,
            "result":   "",
        },
        config=_config(thread),
    )

    # ── Step 2: human reads the plan ────────────────────────────────────
    paused = get_current_state(thread)
    print(f"\nStep 2: Graph is paused. Human reviews the plan.")
    print(f"  Next node: execute | approved={paused['approved']}")

    # ── Step 3: human approves ──────────────────────────────────────────
    print("\nStep 3: Human approves.")
    approve(thread)

    # ── Step 4: resume ──────────────────────────────────────────────────
    print("\nStep 4: Resume execution.")
    final = resume(thread)
    print(f"\nFinal result (excerpt):\n{final['result'][:300]}")


def demo_rejected() -> None:
    """Flow where the human does NOT approve."""
    thread = "hitl-rejected"
    print(f"\n{'=' * 60}")
    print("DEMO 2 — Rejected flow")
    print(f"{'=' * 60}")

    # Invoke — pauses after plan
    print("\nStep 1: Invoke (graph pauses after planning)")
    graph.invoke(
        {
            "task":     "Drop the sessions table and recreate it from scratch",
            "plan":     "",
            "approved": False,
            "result":   "",
        },
        config=_config(thread),
    )

    # Human reviews but rejects
    print("\nStep 2: Human rejects — does not call approve().")
    reject(thread)

    # Resume without approving — execute_node sees approved=False and cancels
    print("\nStep 3: Resume (approved=False).")
    final = resume(thread)
    print(f"\nFinal result: {final['result']}")


if __name__ == "__main__":
    demo_approved()
    demo_rejected()
